// Private tournament board — the deterministic six-slot board a private
// tournament's entrants draft from. Like the Daily board (lib/daily.ts), it's a
// fixed set of (team, decade) slots in lineup order [G,FLEX,W,FLEX,B] plus a 6th
// BENCH slot (sixth man). But a private board comes in TWO flavors:
//
//   • BLIND  — generated by the SAME weighted, decade-decaying algorithm as the
//              daily board, only SEEDED FROM THE TOURNAMENT UUID instead of a
//              date. Two tournaments with different ids get different boards;
//              the same id always reproduces the same board.
//   • MANUAL — the admin hand-picks six distinct NBA teams (decade-first), and
//              we only validate distinctness + a per-decade cap (NOT positional
//              depth — per spec). Slot order is the admin's; slot 6 is the bench.
//
// And — mirroring lib/dailyGhosts.ts — a private board can be filled with
// board-constrained BOTS when an entrant times out: each bot drafts only from
// THIS board's slots, position-rigged via canPlay, biased toward Game Quality.
//
// This module is NEW and imports the existing daily/queries/positions/scoring
// helpers; it does not modify them.

import type { QueryOptions } from "./motherduck";
import { canPlay, type SlotKind } from "./positions";
import {
  getDecades,
  getPlayableTeams,
  getPlayerIndex,
  getTeamDecades,
  getTeamWeights,
  type IndexedPlayer,
} from "./queries";
import { simulateRoster, type ScoringPlayer } from "./scoring";
import { hashSeed, mulberry32 } from "./tournament";
import type { SimPick } from "./types";

// 5 starter slots in lineup order + 1 bench (sixth man). Mirrors daily.ts.
export const PRIVATE_STARTER_SLOTS = 5;
const PRIVATE_TOTAL_SLOTS = PRIVATE_STARTER_SLOTS + 1;

// Lineup positions for the five starter slots, in board order — same as the
// daily ghosts' KINDS. The 6th slot is the bench (no lineup position).
const KINDS: SlotKind[] = ["G", "FLEX", "W", "FLEX", "B"];

// A combo must have at least this many drafted-eligible players to be a legal
// manual pick. Mirrors queries.ts MIN_PLAYERS_PER_COMBO (not exported there, so
// re-declared locally; keep in sync).
const MIN_PLAYERS_PER_COMBO = 10;

// A manual board may repeat a decade at most this many times (six distinct
// teams, but e.g. two 1990s squads is fine; three is not).
const MAX_PER_DECADE = 2;

export interface PrivateSlot {
  team: string;
  decade: number;
}

export interface PrivateBoard {
  slots: PrivateSlot[]; // exactly 5 starter slots, in lineup order [G,FLEX,W,FLEX,B]
  benchSlot: PrivateSlot; // the 6th (sixth man) — always present on a private board
  mode: "blind" | "manual";
}

// ── (a) BLIND board ─────────────────────────────────────────────────────────

/** Same weighted pick as daily.ts (kept private — daily.ts can't be imported). */
function weightedPick<T>(items: T[], weights: number[], rng: () => number): T {
  const total = weights.reduce((a, b) => a + b, 0);
  let r = rng() * total;
  for (let i = 0; i < items.length; i++) {
    r -= weights[i];
    if (r <= 0) return items[i];
  }
  return items[items.length - 1];
}

/**
 * The deterministic BLIND board for a private tournament. Byte-for-byte the same
 * generation as computeDailyBoard (decade usage decays 90% per use; teams never
 * repeat; deterministic tie-breaks) — the ONLY difference is the seed: it's keyed
 * to the tournament UUID, not a date. Always returns a full six (5 starters +
 * bench); if the data can't fill six distinct (team, decade) slots, it throws.
 */
export async function computeBlindPrivateBoard(
  tournamentId: string,
  options: QueryOptions = {},
): Promise<PrivateBoard> {
  const rng = mulberry32(hashSeed(`private-board:${tournamentId}`));

  const decades = await getDecades(options);
  const playableByDecade = new Map(
    await Promise.all(
      decades.map(
        async (d) =>
          [d, await getPlayableTeams(d, options)] as [number, Set<string>],
      ),
    ),
  );
  const teamWeightsCache = new Map<number, { team: string; weight: number }[]>();
  const teamWeightsFor = async (d: number) => {
    if (!teamWeightsCache.has(d)) {
      teamWeightsCache.set(d, await getTeamWeights(d, options));
    }
    return teamWeightsCache.get(d)!;
  };

  const usedTeams = new Set<string>();
  const usage: Record<number, number> = {};
  const all: PrivateSlot[] = [];

  for (let round = 0; round < PRIVATE_TOTAL_SLOTS; round++) {
    const candidates = decades.filter((d) =>
      [...playableByDecade.get(d)!].some((t) => !usedTeams.has(t)),
    );
    if (candidates.length === 0) break;
    const decade = weightedPick(
      candidates,
      candidates.map((d) => Math.pow(0.1, usage[d] ?? 0)),
      rng,
    );

    const playable = playableByDecade.get(decade)!;
    const pool = (await teamWeightsFor(decade))
      .filter((t) => playable.has(t.team) && !usedTeams.has(t.team))
      .sort((a, b) => b.weight - a.weight || a.team.localeCompare(b.team));
    const team = weightedPick(
      pool.map((t) => t.team),
      pool.map((t) => t.weight),
      rng,
    );

    usedTeams.add(team);
    usage[decade] = (usage[decade] ?? 0) + 1;
    all.push({ team, decade });
  }

  if (all.length < PRIVATE_TOTAL_SLOTS) {
    throw new Error(
      `cannot build a full 6-slot blind board for tournament ${tournamentId}: ` +
        `only ${all.length} distinct (team, decade) slots available`,
    );
  }

  return {
    slots: all.slice(0, PRIVATE_STARTER_SLOTS),
    benchSlot: all[PRIVATE_STARTER_SLOTS],
    mode: "blind",
  };
}

// ── (b) MANUAL board ────────────────────────────────────────────────────────

/**
 * PURE validator for an admin-built manual board. Enforces, in order:
 *   1. exactly 6 slots,
 *   2. each slot well-formed (non-empty team, a numeric decade),
 *   3. six DISTINCT NBA teams (by abbreviation),
 *   4. no decade appears more than twice.
 * Does NOT check positional depth (per spec — that's not pre-validated; an empty
 * combo is caught only by the async playability check below). The first five
 * slots are starters in the admin's order; the sixth is the bench.
 */
export function validateManualBoard(
  slots: PrivateSlot[],
): { ok: true; board: PrivateBoard } | { ok: false; reason: string } {
  if (slots.length !== PRIVATE_TOTAL_SLOTS) {
    return { ok: false, reason: "pick exactly 6 teams" };
  }
  for (const s of slots) {
    if (!s || !s.team || !Number.isFinite(s.decade)) {
      return { ok: false, reason: "every slot needs a team and a decade" };
    }
  }

  const teams = new Set(slots.map((s) => s.team));
  if (teams.size !== PRIVATE_TOTAL_SLOTS) {
    return { ok: false, reason: "six distinct teams — no repeats" };
  }

  const perDecade = new Map<number, number>();
  for (const s of slots) {
    const n = (perDecade.get(s.decade) ?? 0) + 1;
    perDecade.set(s.decade, n);
    if (n > MAX_PER_DECADE) {
      return { ok: false, reason: "a decade can appear at most twice" };
    }
  }

  return {
    ok: true,
    board: {
      slots: slots.slice(0, PRIVATE_STARTER_SLOTS),
      benchSlot: slots[PRIVATE_STARTER_SLOTS],
      mode: "manual",
    },
  };
}

/**
 * Server-side manual-board check: everything validateManualBoard enforces PLUS a
 * data-backed guarantee that each (team, decade) actually has enough players to
 * draft (≥ MIN_PLAYERS_PER_COMBO) — so the picker can't choose an empty combo.
 * Uses getPlayableTeams (the same threshold the slot machine uses) per decade.
 */
export async function validateManualBoardPlayable(
  slots: PrivateSlot[],
  options: QueryOptions = {},
): Promise<{ ok: true; board: PrivateBoard } | { ok: false; reason: string }> {
  const pure = validateManualBoard(slots);
  if (!pure.ok) return pure;

  // For each distinct decade in the board, the set of teams with enough players.
  const decades = [...new Set(slots.map((s) => s.decade))];
  const playableByDecade = new Map(
    await Promise.all(
      decades.map(
        async (d) =>
          [d, await getPlayableTeams(d, options)] as [number, Set<string>],
      ),
    ),
  );

  for (const s of slots) {
    const playable = playableByDecade.get(s.decade);
    if (!playable || !playable.has(s.team)) {
      return {
        ok: false,
        reason: `${s.team} in the ${s.decade}s doesn't have enough players`,
      };
    }
  }

  return pure;
}

// ── Deliverable 2: board-constrained BOTS ────────────────────────────────────
//
// Mirrors lib/dailyGhosts.ts: a bot drafts only from THIS board (each starter
// from its slot's (team, decade), position-rigged via canPlay; the sixth man
// from the bench slot), biased toward Game Quality so the field is human-tough.
// The only differences from dailyGhosts: the board always has a bench (private
// boards are full sixes), and the seed comes from the caller, not a date.

// Bias selection toward higher Game Quality: weight ∝ value^GQ_EXP. A high
// exponent makes bots mostly draft the top one or two players per slot (so they
// field strong, human-like rosters) while the seeded RNG still yields variety.
const GQ_EXP = 4;

/** Pick a player weighted toward higher GQ (value), via the seeded RNG. */
function weightedByGQ(
  players: IndexedPlayer[],
  rng: () => number,
): IndexedPlayer {
  const weights = players.map((p) => Math.pow(Math.max(p.value, 0.01), GQ_EXP));
  const total = weights.reduce((a, b) => a + b, 0);
  let r = rng() * total;
  for (let i = 0; i < players.length; i++) {
    r -= weights[i];
    if (r <= 0) return players[i];
  }
  return players[players.length - 1];
}

/** Map an indexed player into the scoring shape (mirrors hydrateRoster). */
function toScoring(p: IndexedPlayer): ScoringPlayer {
  return {
    gq: p.value, season: p.best_season, mpg: p.mpg,
    pts: p.pts, reb: p.reb, ast: p.ast, stl: p.stl, blk: p.blk,
    fga: p.fga, fg3a: p.fg3a, fg3m: p.fg3m, fta: p.fta, tov: p.tov,
    fgm: p.fgm, ftm: p.ftm,
    tsplus: Number.isFinite(p.tsplus) ? p.tsplus : 1,
    height_in: Number.isFinite(p.height_in) ? p.height_in : 79,
    pos: p.pos ?? null,
    allDef: p.all_def ?? 0,
  };
}

/**
 * One generated bot. The caller (API layer) owns NAMING — it decides whether a
 * bot is "{USERNAME} BOT" or a generic name — so we return only the roster, the
 * sixth man, a precomputed seedNet (same scoring path daily ghosts use), and a
 * stable `index` the caller can map a name onto.
 */
export interface GeneratedPrivateBot {
  index: number; // stable 0-based index (deterministic from the seed)
  roster: SimPick[]; // the five starters, slots 0..4 = [G,FLEX,W,FLEX,B]
  sixth: { entity_id: string; team: string; decade: number };
  seedNet: number;
}

/**
 * Find an assignment of the 5 board slots to the 5 lineup positions
 * [G,FLEX,W,FLEX,B] so each position has ≥1 eligible player (exactly the freedom
 * a human has). `elig[boardSlot][position]` is the eligible-player list. Returns
 * `assignment[position] = boardSlot` (a permutation), or null if none works.
 * Mirrors dailyGhosts.findAssignment; searches in board-slot order so the result
 * is deterministic.
 */
function findAssignment(elig: IndexedPlayer[][][]): number[] | null {
  const used = new Set<number>();
  const assignment: number[] = [];
  const bt = (pos: number): boolean => {
    if (pos === KINDS.length) return true;
    for (let bs = 0; bs < elig.length; bs++) {
      if (used.has(bs) || elig[bs][pos].length === 0) continue;
      used.add(bs);
      assignment[pos] = bs;
      if (bt(pos + 1)) return true;
      used.delete(bs);
    }
    return false;
  };
  return bt(0) ? assignment : null;
}

/**
 * Build `count` board-constrained bots from the player `index`, seeded by `seed`
 * (so the same board + seed always yields the same bots). Each bot is generated
 * from its OWN sub-stream — mulberry32(hashSeed(`${seed}:${index}`)) — so the set
 * is order-independent and a caller can request, say, the first 3 today and 2
 * more later and get the same first 3.
 *
 * Returns [] if the board can't field a legal six (no position assignment, or an
 * empty bench/starter combo) — the same degenerate case dailyGhosts guards.
 */
export function buildPrivateBots(
  board: PrivateBoard,
  index: IndexedPlayer[],
  seed: string,
  count: number,
): GeneratedPrivateBot[] {
  if (board.slots.length < KINDS.length) return [];

  const byCombo = (team: string, decade: number) =>
    index.filter((p) => p.team === team && p.decade === decade);

  // For each board slot, the players it can field at each lineup position.
  const comboPlayers = board.slots.map((s) => byCombo(s.team, s.decade));
  const elig = comboPlayers.map((players) =>
    KINDS.map((kind) => players.filter((p) => canPlay(p, kind))),
  );
  const assignment = findAssignment(elig); // position → board slot
  const benchCands = byCombo(board.benchSlot.team, board.benchSlot.decade);
  if (!assignment || benchCands.length === 0) return [];

  const bots: GeneratedPrivateBot[] = [];
  for (let i = 0; i < count; i++) {
    const rng = mulberry32(hashSeed(`${seed}:${i}`));
    // Position j drafts a (GQ-weighted) eligible player from its assigned slot.
    const starters = KINDS.map((_, pos) => {
      const bs = assignment[pos];
      return { player: weightedByGQ(elig[bs][pos], rng), slot: pos };
    });
    const sixth = weightedByGQ(benchCands, rng);
    const seedNet = simulateRoster(
      starters.map((s) => toScoring(s.player)),
    ).seedNet;
    bots.push({
      index: i,
      roster: starters.map((s) => ({
        entity_id: s.player.entity_id,
        team: s.player.team,
        decade: s.player.decade,
        slot: s.slot,
      })),
      sixth: {
        entity_id: sixth.entity_id,
        team: sixth.team,
        decade: sixth.decade,
      },
      seedNet,
    });
  }
  return bots;
}

/**
 * Convenience server-side wrapper: load the player index, then buildPrivateBots.
 * Kept separate so the core builder stays pure/testable without a DB.
 */
export async function generatePrivateBots(
  board: PrivateBoard,
  seed: string,
  count: number,
  options: QueryOptions = {},
): Promise<GeneratedPrivateBot[]> {
  const index = await getPlayerIndex(options);
  return buildPrivateBots(board, index, seed, count);
}

// Re-export so callers building the manual picker can reuse the same combo list.
export { getTeamDecades, getDecades };
