// Private tournament board — the deterministic six-slot board a private
// tournament's entrants draft from. Like the Daily board (lib/daily.ts), it's a
// fixed set of (team, decade) slots in lineup order [G,FLEX,W,FLEX,B] plus a 6th
// BENCH slot (sixth man). But a private board comes in TWO flavors:
//
//   • BLIND  — generated by the SAME weighted, decade-decaying algorithm as the
//              daily board, only SEEDED FROM THE TOURNAMENT UUID instead of a
//              date. Two tournaments with different ids get different boards;
//              the same id always reproduces the same board.
//   • MANUAL — the admin hand-picks six distinct NBA teams (decade-first), and
//              we only validate distinctness + a per-decade cap (NOT positional
//              depth — per spec). Slot order is the admin's; slot 6 is the bench.
//
// And — mirroring lib/dailyGhosts.ts — a private board can be filled with
// board-constrained BOTS when an entrant times out: each bot drafts only from
// THIS board's slots, position-rigged via canPlay, biased toward Game Quality.
//
// This module is NEW and imports the existing daily/queries/positions/scoring
// helpers; it does not modify them.

import { buildTeamDecadeBoard } from "./boardGen";
import type { QueryOptions } from "./motherduck";
import { canPlay, type SlotKind } from "./positions";
import {
  getDecades,
  getPlayableTeams,
  getPlayerIndex,
  getTeamDecades,
  type IndexedPlayer,
} from "./queries";
import {
  PRIVATE_STARTER_SLOTS,
  PRIVATE_TOTAL_SLOTS,
  validateManualBoard,
  type PrivateBoard,
  type PrivateSlot,
} from "./privateBoardRules";
import { simulateRoster, type ScoringPlayer } from "./scoring";
import { hashSeed, mulberry32 } from "./tournament";
import type { SimPick } from "./types";

// The pure board types/constants/validator live in the client-safe rules module
// (lib/privateBoardRules.ts) so the client form and this server module can't
// drift. Re-export them here for existing importers of "@/lib/privateBoard".
export {
  PRIVATE_STARTER_SLOTS,
  MAX_PER_DECADE,
  validateManualBoard,
} from "./privateBoardRules";
export type { PrivateSlot, PrivateBoard } from "./privateBoardRules";

// Lineup positions for the five starter slots, in board order — same as the
// daily ghosts' KINDS. The 6th slot is the bench (no lineup position).
const KINDS: SlotKind[] = ["G", "FLEX", "W", "FLEX", "B"];

// A combo must have at least this many drafted-eligible players to be a legal
// manual pick. Mirrors queries.ts MIN_PLAYERS_PER_COMBO (not exported there, so
// re-declared locally; keep in sync).
const MIN_PLAYERS_PER_COMBO = 10;

// ── (a) BLIND board ─────────────────────────────────────────────────────────

/**
 * The deterministic BLIND board for a private tournament. Uses the shared
 * buildTeamDecadeBoard generator (decade usage decays 90% per use; teams never
 * repeat; deterministic tie-breaks); the seed is keyed to the tournament UUID,
 * and requireFull makes it always return a full six (5 starters + bench),
 * throwing if the data can't fill six distinct (team, decade) slots.
 *
 * Decade weighting is "byTeamCount" (eras in proportion to their team count) —
 * this runs ONLY at creation, and the resulting board is frozen in
 * private_tournaments.board_json. Every read path uses that stored board, so
 * existing tournaments are unaffected; only newly created boards see this.
 */
export async function computeBlindPrivateBoard(
  tournamentId: string,
  options: QueryOptions = {},
): Promise<PrivateBoard> {
  const all = await buildTeamDecadeBoard({
    seed: `private-board:${tournamentId}`,
    totalSlots: PRIVATE_TOTAL_SLOTS,
    requireFull: true,
    decadeWeighting: "byTeamCount",
    options,
  });

  return {
    slots: all.slice(0, PRIVATE_STARTER_SLOTS),
    benchSlot: all[PRIVATE_STARTER_SLOTS],
    mode: "blind",
  };
}

// ── (b) MANUAL board ────────────────────────────────────────────────────────
//
// The PURE validateManualBoard (slot count, distinct teams, per-decade cap) now
// lives in lib/privateBoardRules.ts and is imported above. The server adds only
// the async playability check below on top of it.

/**
 * Server-side manual-board check: everything validateManualBoard enforces PLUS a
 * data-backed guarantee that each (team, decade) actually has enough players to
 * draft (≥ MIN_PLAYERS_PER_COMBO) — so the picker can't choose an empty combo.
 * Uses getPlayableTeams (the same threshold the slot machine uses) per decade.
 */
export async function validateManualBoardPlayable(
  slots: PrivateSlot[],
  options: QueryOptions = {},
): Promise<{ ok: true; board: PrivateBoard } | { ok: false; reason: string }> {
  const pure = validateManualBoard(slots);
  if (!pure.ok) return pure;

  // For each distinct decade in the board, the set of teams with enough players.
  const decades = [...new Set(slots.map((s) => s.decade))];
  const playableByDecade = new Map(
    await Promise.all(
      decades.map(
        async (d) =>
          [d, await getPlayableTeams(d, options)] as [number, Set<string>],
      ),
    ),
  );

  for (const s of slots) {
    const playable = playableByDecade.get(s.decade);
    if (!playable || !playable.has(s.team)) {
      return {
        ok: false,
        reason: `${s.team} in the ${s.decade}s doesn't have enough players`,
      };
    }
  }

  return pure;
}

// ── Deliverable 2: board-constrained BOTS ────────────────────────────────────
//
// Mirrors lib/dailyGhosts.ts: a bot drafts only from THIS board (each starter
// from its slot's (team, decade), position-rigged via canPlay; the sixth man
// from the bench slot), biased toward Game Quality so the field is human-tough.
// The only differences from dailyGhosts: the board always has a bench (private
// boards are full sixes), and the seed comes from the caller, not a date.

// Bias selection toward higher Game Quality: weight ∝ value^GQ_EXP. A high
// exponent makes bots mostly draft the top one or two players per slot (so they
// field strong, human-like rosters) while the seeded RNG still yields variety.
const GQ_EXP = 4;

/** Pick a player weighted toward higher GQ (value), via the seeded RNG. */
function weightedByGQ(
  players: IndexedPlayer[],
  rng: () => number,
): IndexedPlayer {
  const weights = players.map((p) => Math.pow(Math.max(p.value, 0.01), GQ_EXP));
  const total = weights.reduce((a, b) => a + b, 0);
  let r = rng() * total;
  for (let i = 0; i < players.length; i++) {
    r -= weights[i];
    if (r <= 0) return players[i];
  }
  return players[players.length - 1];
}

/** Map an indexed player into the scoring shape (mirrors hydrateRoster). */
function toScoring(p: IndexedPlayer): ScoringPlayer {
  return {
    gq: p.value, season: p.best_season, mpg: p.mpg,
    pts: p.pts, reb: p.reb, ast: p.ast, stl: p.stl, blk: p.blk,
    fga: p.fga, fg3a: p.fg3a, fg3m: p.fg3m, fta: p.fta, tov: p.tov,
    fgm: p.fgm, ftm: p.ftm,
    tsplus: Number.isFinite(p.tsplus) ? p.tsplus : 1,
    height_in: Number.isFinite(p.height_in) ? p.height_in : 79,
    pos: p.pos ?? null,
    allDef: p.all_def ?? 0,
  };
}

/**
 * One generated bot. The caller (API layer) owns NAMING — it decides whether a
 * bot is "{USERNAME} BOT" or a generic name — so we return only the roster, the
 * sixth man, a precomputed seedNet (same scoring path daily ghosts use), and a
 * stable `index` the caller can map a name onto.
 */
export interface GeneratedPrivateBot {
  index: number; // stable 0-based index (deterministic from the seed)
  roster: SimPick[]; // the five starters, slots 0..4 = [G,FLEX,W,FLEX,B]
  sixth: { entity_id: string; team: string; decade: number };
  seedNet: number;
}

/**
 * Find an assignment of the 5 board slots to the 5 lineup positions
 * [G,FLEX,W,FLEX,B] so each position has ≥1 eligible player (exactly the freedom
 * a human has). `elig[boardSlot][position]` is the eligible-player list. Returns
 * `assignment[position] = boardSlot` (a permutation), or null if none works.
 * Mirrors dailyGhosts.findAssignment; searches in board-slot order so the result
 * is deterministic.
 */
function findAssignment(elig: IndexedPlayer[][][]): number[] | null {
  const used = new Set<number>();
  const assignment: number[] = [];
  const bt = (pos: number): boolean => {
    if (pos === KINDS.length) return true;
    for (let bs = 0; bs < elig.length; bs++) {
      if (used.has(bs) || elig[bs][pos].length === 0) continue;
      used.add(bs);
      assignment[pos] = bs;
      if (bt(pos + 1)) return true;
      used.delete(bs);
    }
    return false;
  };
  return bt(0) ? assignment : null;
}

/**
 * Build `count` board-constrained bots from the player `index`, seeded by `seed`
 * (so the same board + seed always yields the same bots). Each bot is generated
 * from its OWN sub-stream — mulberry32(hashSeed(`${seed}:${index}`)) — so the set
 * is order-independent and a caller can request, say, the first 3 today and 2
 * more later and get the same first 3.
 *
 * Returns [] if the board can't field a legal six (no position assignment, or an
 * empty bench/starter combo) — the same degenerate case dailyGhosts guards.
 */
export function buildPrivateBots(
  board: PrivateBoard,
  index: IndexedPlayer[],
  seed: string,
  count: number,
): GeneratedPrivateBot[] {
  if (board.slots.length < KINDS.length) return [];

  const byCombo = (team: string, decade: number) =>
    index.filter((p) => p.team === team && p.decade === decade);

  // For each board slot, the players it can field at each lineup position.
  const comboPlayers = board.slots.map((s) => byCombo(s.team, s.decade));
  const elig = comboPlayers.map((players) =>
    KINDS.map((kind) => players.filter((p) => canPlay(p, kind))),
  );
  const assignment = findAssignment(elig); // position → board slot
  const benchCands = byCombo(board.benchSlot.team, board.benchSlot.decade);
  if (!assignment || benchCands.length === 0) return [];

  const bots: GeneratedPrivateBot[] = [];
  for (let i = 0; i < count; i++) {
    const rng = mulberry32(hashSeed(`${seed}:${i}`));
    // Position j drafts a (GQ-weighted) eligible player from its assigned slot.
    const starters = KINDS.map((_, pos) => {
      const bs = assignment[pos];
      return { player: weightedByGQ(elig[bs][pos], rng), slot: pos };
    });
    const sixth = weightedByGQ(benchCands, rng);
    const seedNet = simulateRoster(
      starters.map((s) => toScoring(s.player)),
    ).seedNet;
    bots.push({
      index: i,
      roster: starters.map((s) => ({
        entity_id: s.player.entity_id,
        team: s.player.team,
        decade: s.player.decade,
        slot: s.slot,
      })),
      sixth: {
        entity_id: sixth.entity_id,
        team: sixth.team,
        decade: sixth.decade,
      },
      seedNet,
    });
  }
  return bots;
}

/**
 * Convenience server-side wrapper: load the player index, then buildPrivateBots.
 * Kept separate so the core builder stays pure/testable without a DB.
 */
export async function generatePrivateBots(
  board: PrivateBoard,
  seed: string,
  count: number,
  options: QueryOptions = {},
): Promise<GeneratedPrivateBot[]> {
  const index = await getPlayerIndex(options);
  return buildPrivateBots(board, index, seed, count);
}

// Re-export so callers building the manual picker can reuse the same combo list.
export { getTeamDecades, getDecades };
