// Shared UUID validation. Two distinct patterns exist in this codebase — do
// not merge them:
//
// - isUuid(): loose 8-4-4-4-12 hex shape check (any version/variant nibble).
//   This is what every API route uses to validate ids that were generated by
//   `randomUUID()` and round-tripped through a URL or request body — the
//   route only needs to know "is this shaped like a UUID" before using it in
//   a query, not "is this a spec-compliant RFC 4122 UUID".
// - isUuidStrict(): also constrains the version nibble (1-5) and variant
//   nibble (8/9/a/b) per RFC 4122. lib/sessionHint.ts uses this because it is
//   validating a value the client sent back in a cookie — untrusted input —
//   before trusting it as a session identifier, so the extra constraint is
//   intentional defense-in-depth (rejects clearly-forged cookie values that
//   merely look hex-shaped). Node's `randomUUID()` always emits version 4 /
//   variant 1 UUIDs, so real session hints always satisfy this stricter
//   check too.

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const UUID_STRICT_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function isUuid(v: unknown): v is string {
  return typeof v === "string" && UUID_RE.test(v);
}

export function isUuidStrict(v: unknown): v is string {
  return typeof v === "string" && UUID_STRICT_RE.test(v);
}
